/*
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will
    be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms
    in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
*/

#include <stdio.h>

#define LIMIT 4000000

int main()
{
    int fib, fib1, fib2, fib_sum;

    fib1 = 0;
    fib2 = 1;
    fib_sum = 0;

    fib = fib1 + fib2;
    while (fib <= LIMIT)
    {
        if (((fib % 2) == 0))
            fib_sum += fib;

        fib1 = fib2;
        fib2 = fib;
        fib = fib1 + fib2;
    }

    printf("sum: %d\n", fib_sum);

    return 0;
}
